# WARNING: this file is not suitable for production, please use with caution
version: '3.4'

services:
  web:
    image: map
    build: .
    command: map run -h 0.0.0.0
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=${DATABASE_URI}
    volumes:
      - ./map:/code/map
      - ./db/:/db/
    ports:
      - "${EXTERNAL_PORT}:5000"
  couch:
    image: couchdb:2.3.1
    environment:
      COUCHDB_USER: couchdb_user
      # read from .env
      COUCHDB_SECRET: ${COUCHDB_SECRET:-couchdb_secret}
    ports:
      - "5984:5984"
    volumes:
      - source: couchdb-data
        target: /opt/couchdb/data
        type: volume
volumes:
  couchdb-data: {}
