---
version: "3.4"
services:
  web:
    build:
      context: .
    volumes:
      #- ./:/opt/app
      - ./map:/code/map
    ports:
      # allow override of published port
      - ${EXTERNAL_PORT:-5000}:5000
    env_file:
      - auth_proxy.env
