# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: map
    build: .
    command: map run -h 0.0.0.0
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/map.db
    volumes:
      - ./map:/code/map
      - ./db/:/db/
    ports:
      - "${EXTERNAL_PORT}:5000"
