---
version: "3.4"
services:
  web:
    image: "uwcirg/map-api:${DOCKER_IMAGE_TAG:-develop}"
    build:
      context: .
    ports:
      # allow override of published port
      - ${EXTERNAL_PORT:-5000}:5000
    env_file:
      - auth_proxy.env
