---
name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Publish to Dockerhub registry
      # todo: pin to hash
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: uwcirg/map-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
